"""made name field in Category unique=False


Revision ID: 28fefc18d643
Revises: cf75424f41da
Create Date: 2024-08-04 13:23:42.099120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fefc18d643'
down_revision = 'cf75424f41da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_name')
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.create_index('ix_category_name', ['name'], unique=1)

    # ### end Alembic commands ###
