"""Initial Migration UCTB 

Revision ID: 4020c7e3ff7e
Revises: 8e36fb63802f
Create Date: 2024-07-30 08:21:03.007648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4020c7e3ff7e'
down_revision = '8e36fb63802f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_category_user_id'), ['user_id'], unique=False)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=30), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('loan_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_loan_type'), ['loan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')
        batch_op.drop_index('ix_post_user_id')

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_timestamp'))
        batch_op.drop_column('timestamp')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_loan_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_category_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_amount'))

    op.drop_table('transaction')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_user_id'))
        batch_op.drop_index(batch_op.f('ix_budget_category_id'))
        batch_op.drop_index(batch_op.f('ix_budget_amount'))

    op.drop_table('budget')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    # ### end Alembic commands ###
